apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - services
      - pods
    verbs:
      - get
      - watch
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail-serviceaccount

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: promtail-serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: promtail-clusterrole
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail-config.yaml: |-
    server:
      http_listen_port: 9080
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://192.168.10.133:3100/loki/api/v1/push  # Cập nhật địa chỉ Loki của bạn
    scrape_configs:
      - job_name: kubernetes-pods
        static_configs:
        - targets:
            - localhost
          labels:
            job: varlogs
            __path__: /var/log/*/*.log

--- 

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail-daemonset
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
      - name: promtail
        image: grafana/promtail:latest  # Thay đổi tag image tùy theo phiên bản mong muốn
        args:
        - -config.file=/etc/promtail/promtail-config.yaml
        volumeMounts:
        - name: promtail-config
          mountPath: /etc/promtail
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: promtail-config
        configMap:
          name: promtail-config



````

apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail-config.yaml: |-
    server:
      http_listen_port: 9080
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://192.168.10.133:3100/loki/api/v1/push  # Cập nhật địa chỉ Loki của bạn
    scrape_configs:
      - job_name: kubernetes-pods
        static_configs:
        - targets:
            - localhost
          labels:
            job: varlogs
            __path__: /var/log/*/*.log
        kubernetes_sd_configs:
        - role: pod
          selectors:
          - role: pod
            label: redis-streams-act-9bcdbbbdd-9f45g


----------------------

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail-pod-reader-binding
subjects:
- kind: ServiceAccount
  name: default  # Sử dụng ServiceAccount mặc định của namespace
  namespace: default
roleRef:
  kind: ClusterRole
  name: promtail-pod-reader
  apiGroup: rbac.authorization.k8s.io


---------------------- 

# Configmap 

apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail-config.yaml: |-
    server:
      http_listen_port: 9080
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://192.168.10.133:3100/loki/api/v1/push  # Cập nhật địa chỉ Loki của bạn
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __path__
          regex: (.+)
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          target_label: __port__
          regex: (.+)


--------------------

apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail-config.yaml: |-
    server:
      http_listen_port: 9080
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://192.168.10.133:3100/loki/api/v1/push  # Cập nhật địa chỉ Loki của bạn
    scrape_configs:
      - job_name: kubernetes-pods
        static_configs:

        - targets:
            - localhost
          labels:
            job: helloooo
            __path__: /var/log/*/*.log

        - targets:
            - localhost
          labels:
            job: Hieu thu 2
            __path__: /var/log/*/*.log


------------------------------



apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail-config.yaml: |-
    server:
      http_listen_port: 9080
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://192.168.10.133:3100/loki/api/v1/push
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: redis-streams-act-6544d8dd67-fk7h2
        pipeline_stages:
          - docker: {}



////


apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail-config.yaml: |-
    server:
      http_listen_port: 9080
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://192.168.10.133:3100/loki/api/v1/push  # Cập nhật địa chỉ Loki của bạn
    scrape_configs:
      - job_name: varlogs
        static_configs:
        - targets:
            - localhost
          labels:
            job: varlogs
            __path__: /var/log/*/*.log

      - job_name: kubernetes-pods-redis-streams
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_name]
            action: keep
            regex: redis-streams-act-6c85ddb784-6vv5r
        pipeline_stages:
          - docker: {}



///


http://192.168.10.133:3100/

config:
  # publish data to loki
  clients:
    - url: http://192.168.10.133:3100/loki/api/v1/push
      tenant_id: 1