{
 "title": "Liberty-Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "servlet",
    "label": "Servlet",
    "query": "{__name__=~\"vendor:servlet.*_response_time_total_seconds\"}"
   },
   { "name": "dur", "label": "Moving Average", "query": "${VAR_DUR}" },
   {
    "name": "connection_pools",
    "query": "metrics([^_]*connectionpool_.*_managed_connections)"
   },
   {
    "name": "thread_pools",
    "query": "metrics([^_]*threadpool_.*_active_threads)"
   }
  ]
 },
 "panels": [
  { "title": "Servlet (${servlet})", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "servlet" },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(vendor:servlet_${servlet}_request_total[$dur])",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(vendor:servlet_${servlet}_response_time_total_seconds[$dur])/rate(vendor:servlet_${servlet}_request_total[$dur])",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "title": "Connection Pool (${connection_pools})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "connection_pools",
   "collapsed": true,
   "panels": [
    {
     "title": "Used connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(vendor:connectionpool_${connection_pools}_used_connections_total[$dur])",
       "legendFormat": "Used connections"
      }
     ]
    },
    {
     "title": "In Use Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(vendor:connectionpool_${connection_pools}_in_use_time_total_seconds[$dur])/rate(vendor:connectionpool_${connection_pools}_used_connections_total[$dur])",
       "legendFormat": "In use time"
      }
     ]
    },
    {
     "title": "Wait Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(vendor:connectionpool_${connection_pools}_wait_time_total_seconds[$dur])/rate(vendor:connectionpool_${connection_pools}_used_connections_total[$dur])",
       "legendFormat": "Wait time"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor:connectionpool_${connection_pools}_managed_connections",
       "legendFormat": "Managed"
      },
      {
       "expr": "vendor:connectionpool_${connection_pools}_connection_handles",
       "legendFormat": "Used"
      },
      {
       "expr": "vendor:connectionpool_${connection_pools}_free_connections",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Created / destroyed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(vendor:connectionpool_${connection_pools}_create_total[$dur])",
       "legendFormat": "Created"
      },
      {
       "expr": "increase(vendor:connectionpool_${connection_pools}_destroy_total[$dur])",
       "legendFormat": "Destroyed"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool (${thread_pools})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "thread_pools",
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor:threadpool_default_executor_active_threads",
       "legendFormat": "Active"
      },
      {
       "expr": "vendor:threadpool_default_executor_size",
       "legendFormat": "Pool size"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor:session_default_host_metrics_active_sessions",
       "legendFormat": "Active"
      },
      {
       "expr": "vendor:session_default_host_metrics_live_sessions",
       "legendFormat": "Live"
      }
     ]
    },
    {
     "title": "Created / Invalidated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(vendor:session_default_host_metrics_create_total[$dur])",
       "legendFormat": "Created"
      },
      {
       "expr": "increase(vendor:session_default_host_metrics_invalidated_total[$dur])",
       "legendFormat": "Invalidated"
      }
     ]
    }
   ]
  },
  {
   "title": "System Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load Percent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "base:cpu_process_cpu_load_percent",
       "legendFormat": "CPU load"
      }
     ]
    },
    {
     "title": "CPU System Load Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "base:cpu_system_load_average", "legendFormat": "System load average" }
     ]
    },
    {
     "title": "Available CPU Processors",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "base:cpu_available_processors" }
     ]
    },
    {
     "title": "Heap Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(base:memory_used_heap_bytes/base:memory_max_heap_bytes)",
       "legendFormat": "Heap usage"
      }
     ]
    },
    {
     "title": "Used Heap",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 27 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      { "expr": "base:memory_used_heap_bytes" }
     ]
    },
    {
     "title": "Max Heap Size",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 27 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      { "expr": "base:memory_max_heap_bytes" }
     ]
    },
    {
     "title": "JVM Uptime",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 35 },
     "format": "s",
     "valueName": "current",
     "targets": [
      { "expr": "base:jvm_uptime_seconds" }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "base:thread_count", "legendFormat": "Threads" },
      { "expr": "base:thread_daemon_count", "legendFormat": "Daemon threads" }
     ]
    },
    {
     "title": "Loaded / Unloaded Classes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(base:classloader_total_loaded_class_count[$dur])",
       "legendFormat": "Loaded"
      },
      {
       "expr": "rate(base:classloader_total_unloaded_class_count[$dur])",
       "legendFormat": "Unloaded"
      }
     ]
    },
    {
     "title": "Loaded Classes",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 43 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "base:classloader_current_loaded_class_count"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time per Scavenge GC Cycle",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(base:gc_scavenge_time_seconds[$dur]) / rate(base:gc_scavenge_count[$dur])",
       "legendFormat": "Time per scavenge GC"
      }
     ]
    },
    {
     "title": "Time per Global GC Cycle",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(base:gc_global_time_seconds[$dur]) / rate(base:gc_global_count[$dur])",
       "legendFormat": "Time per global GC"
      }
     ]
    }
   ]
  }
 ]
}