# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-redis-streams
  namespace: default
spec:
  replicas: 10
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: api-redis-streams
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-redis-streams
    spec:
      containers:
      - name: api-redis-streams
        image: linhtran2023/actsone_performance_system:v09
        resources: {}
      restartPolicy: Always

---
# Service
apiVersion: v1
kind: Service
metadata:
spec:
  ports:
  - nodePort: 30000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: api-redis-streams
  sessionAffinity: None
  type: NodePort


---

apiVersion: v1
kind: Service
metadata:
  name: api-redis-streams
  namespace: default
spec:
  selector:
    app: api-redis-streams
  ports:
  - nodePort: 30000
    port: 5000
    protocol: TCP
    targetPort: 5000
  type: NodePort

