# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-streams-act
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis-streams-act
  template:
    metadata:
      labels:
        app: redis-streams-act
    spec:
      containers:
      - name: redis-streams-act
        image: linhtran2023/actsone_performance_system:v09
        resources: {}
      restartPolicy: Always
---
# Service
apiVersion: v1
kind: Service
metadata:
spec:
  ports:
  - nodePort: 30000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: actsone-message
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

---