# Deployment not control the source
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-producer-kafka-no-control-source
  labels:
    app: api-producer-kafka-no-control-source
spec:
  replicas: 1  # Số lượng replicas bạn muốn triển khai
  selector:
    matchLabels:
      app: api-producer-kafka-no-control-source
  template:
    metadata:
      labels:
        app: api-producer-kafka-no-control-source
    spec:
      containers:
      - name: api-producer-kafka-no-control-source
        image: linhtran2023/api-consumer-kafka-control-source:v15

# SVC
apiVersion: v1
kind: Service
metadata:
  name: api-producer-kafka-no-control-source
spec:
  type: NodePort
  ports:
    - port: 80  # Cổng exposed bởi Service
      targetPort: 5000  # Cổng của target pod
      nodePort: 30005
  selector:
    app: api-producer-kafka-no-control-source

---

# Deployment Have Control the Source
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-producer-kafka-basic-2
  labels:
    app: api-producer-kafka-basic-2
spec:
  replicas: 1  # Số lượng replicas bạn muốn triển khai
  selector:
    matchLabels:
      app: api-producer-kafka-basic-2
  template:
    metadata:
      labels:
        app: api-producer-kafka-basic-2
    spec:
      containers:
      - name: api-producer-kafka-basic-2
        image: linhtran2023/deploy_kafka_producer:v08
        resources:
          limits:
            cpu: "300m"  # Giới hạn 60% của 1 core
            memory: "300Mi"  # Giới hạn 200Mi RAM
          requests:
            cpu: "200m"  # Yêu cầu ít nhất 100m CPU
            memory: "200Mi"  # Yêu cầu ít nhất 100Mi RAM

---

# Service have control source --------------------------
apiVersion: v1
kind: Service
metadata:
  name: api-producer-kafka-basic-2
spec:
  type: NodePort
  ports:
    - port: 80  # Cổng exposed bởi Service
      targetPort: 5000  # Cổng của target pod
      nodePort: 30000
  selector:
    app: api-producer-kafka-basic-2 


# This help for auto scale the pod  -------------------
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-producer-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-producer-kafka-basic-2
  minReplicas: 1 # This min Pod
  maxReplicas: 10 # This max Pod
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50 # This 50% resource server
